---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ebrown/capstone:frontend
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /gotmeals/_stcore/health
              port: 8501
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /gotmeals/_stcore/health
              port: 8501
            initialDelaySeconds: 15
            periodSeconds: 20
