---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8000
      protocol: TCP
  selector:
    app: frontend
