---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          image: w255mids.azurecr.io/edbrown/elasticsearch:8.12.2
          resources:
            requests:
              cpu: 1000m
              memory: 2048Mi
            limits:
              cpu: 2100m
              memory: 2048Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-pw
                  key: ELASTIC_PASSWORD

