---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: lab4
spec:
  hosts:
    - edbrown.mids255.com
  gateways:
    - istio-ingress/edbrown-gateway
  http:
    - match:
      - uri:
          exact: /predict
      - uri:
          exact: /health
      - uri:
          exact: /docs
      - uri:
          exact: /openapi.json
      - uri:
          exact: /version
      - uri:
          exact: /classes
      route:
      - destination:
          host: lab4
          port:
            number: 8888
    - match:
      - uri:
          exact: /gotmeals
      route:
      - destination:
          host: frontend
          port:
            number: 8501
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: elasticsearch
          port:
            number: 9200
